/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.mdd.cw2.pageGenerator.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.kcl.mdd.cw2.pageGenerator.parser.antlr.internal.InternalPageGeneratorLanguareParser;
import uk.ac.kcl.mdd.cw2.pageGenerator.services.PageGeneratorLanguareGrammarAccess;

public class PageGeneratorLanguareParser extends AbstractAntlrParser {

	@Inject
	private PageGeneratorLanguareGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPageGeneratorLanguareParser createParser(XtextTokenStream stream) {
		return new InternalPageGeneratorLanguareParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "WebPage";
	}

	public PageGeneratorLanguareGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PageGeneratorLanguareGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
