/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.mdd.cw2.pageGenerator.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PageGeneratorLanguareUiModule extends AbstractPageGeneratorLanguareUiModule {

	public PageGeneratorLanguareUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
