/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.PageGeneratorLanguarePackage;
import uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.Picture;
import uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.locationexpression;
import uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.primarySize;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Picture</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.impl.PictureImpl#getSize <em>Size</em>}</li>
 *   <li>{@link uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.impl.PictureImpl#getAlt <em>Alt</em>}</li>
 *   <li>{@link uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.impl.PictureImpl#getLocation <em>Location</em>}</li>
 *   <li>{@link uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.impl.PictureImpl#getLpadding <em>Lpadding</em>}</li>
 *   <li>{@link uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.impl.PictureImpl#getRpadding <em>Rpadding</em>}</li>
 *   <li>{@link uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.impl.PictureImpl#getTpadding <em>Tpadding</em>}</li>
 *   <li>{@link uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.impl.PictureImpl#getBpadding <em>Bpadding</em>}</li>
 *   <li>{@link uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.impl.PictureImpl#getPicUrl <em>Pic Url</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PictureImpl extends bodyElementImpl implements Picture
{
  /**
   * The cached value of the '{@link #getSize() <em>Size</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSize()
   * @generated
   * @ordered
   */
  protected primarySize size;

  /**
   * The default value of the '{@link #getAlt() <em>Alt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAlt()
   * @generated
   * @ordered
   */
  protected static final String ALT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAlt() <em>Alt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAlt()
   * @generated
   * @ordered
   */
  protected String alt = ALT_EDEFAULT;

  /**
   * The cached value of the '{@link #getLocation() <em>Location</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocation()
   * @generated
   * @ordered
   */
  protected locationexpression location;

  /**
   * The default value of the '{@link #getLpadding() <em>Lpadding</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLpadding()
   * @generated
   * @ordered
   */
  protected static final int LPADDING_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getLpadding() <em>Lpadding</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLpadding()
   * @generated
   * @ordered
   */
  protected int lpadding = LPADDING_EDEFAULT;

  /**
   * The default value of the '{@link #getRpadding() <em>Rpadding</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRpadding()
   * @generated
   * @ordered
   */
  protected static final int RPADDING_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getRpadding() <em>Rpadding</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRpadding()
   * @generated
   * @ordered
   */
  protected int rpadding = RPADDING_EDEFAULT;

  /**
   * The default value of the '{@link #getTpadding() <em>Tpadding</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTpadding()
   * @generated
   * @ordered
   */
  protected static final int TPADDING_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getTpadding() <em>Tpadding</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTpadding()
   * @generated
   * @ordered
   */
  protected int tpadding = TPADDING_EDEFAULT;

  /**
   * The default value of the '{@link #getBpadding() <em>Bpadding</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBpadding()
   * @generated
   * @ordered
   */
  protected static final int BPADDING_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getBpadding() <em>Bpadding</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBpadding()
   * @generated
   * @ordered
   */
  protected int bpadding = BPADDING_EDEFAULT;

  /**
   * The default value of the '{@link #getPicUrl() <em>Pic Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPicUrl()
   * @generated
   * @ordered
   */
  protected static final String PIC_URL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPicUrl() <em>Pic Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPicUrl()
   * @generated
   * @ordered
   */
  protected String picUrl = PIC_URL_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PictureImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PageGeneratorLanguarePackage.Literals.PICTURE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public primarySize getSize()
  {
    return size;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSize(primarySize newSize, NotificationChain msgs)
  {
    primarySize oldSize = size;
    size = newSize;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PageGeneratorLanguarePackage.PICTURE__SIZE, oldSize, newSize);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSize(primarySize newSize)
  {
    if (newSize != size)
    {
      NotificationChain msgs = null;
      if (size != null)
        msgs = ((InternalEObject)size).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PageGeneratorLanguarePackage.PICTURE__SIZE, null, msgs);
      if (newSize != null)
        msgs = ((InternalEObject)newSize).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PageGeneratorLanguarePackage.PICTURE__SIZE, null, msgs);
      msgs = basicSetSize(newSize, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PageGeneratorLanguarePackage.PICTURE__SIZE, newSize, newSize));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getAlt()
  {
    return alt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAlt(String newAlt)
  {
    String oldAlt = alt;
    alt = newAlt;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PageGeneratorLanguarePackage.PICTURE__ALT, oldAlt, alt));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public locationexpression getLocation()
  {
    return location;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLocation(locationexpression newLocation, NotificationChain msgs)
  {
    locationexpression oldLocation = location;
    location = newLocation;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PageGeneratorLanguarePackage.PICTURE__LOCATION, oldLocation, newLocation);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLocation(locationexpression newLocation)
  {
    if (newLocation != location)
    {
      NotificationChain msgs = null;
      if (location != null)
        msgs = ((InternalEObject)location).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PageGeneratorLanguarePackage.PICTURE__LOCATION, null, msgs);
      if (newLocation != null)
        msgs = ((InternalEObject)newLocation).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PageGeneratorLanguarePackage.PICTURE__LOCATION, null, msgs);
      msgs = basicSetLocation(newLocation, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PageGeneratorLanguarePackage.PICTURE__LOCATION, newLocation, newLocation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getLpadding()
  {
    return lpadding;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLpadding(int newLpadding)
  {
    int oldLpadding = lpadding;
    lpadding = newLpadding;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PageGeneratorLanguarePackage.PICTURE__LPADDING, oldLpadding, lpadding));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getRpadding()
  {
    return rpadding;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRpadding(int newRpadding)
  {
    int oldRpadding = rpadding;
    rpadding = newRpadding;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PageGeneratorLanguarePackage.PICTURE__RPADDING, oldRpadding, rpadding));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getTpadding()
  {
    return tpadding;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTpadding(int newTpadding)
  {
    int oldTpadding = tpadding;
    tpadding = newTpadding;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PageGeneratorLanguarePackage.PICTURE__TPADDING, oldTpadding, tpadding));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getBpadding()
  {
    return bpadding;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBpadding(int newBpadding)
  {
    int oldBpadding = bpadding;
    bpadding = newBpadding;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PageGeneratorLanguarePackage.PICTURE__BPADDING, oldBpadding, bpadding));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPicUrl()
  {
    return picUrl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPicUrl(String newPicUrl)
  {
    String oldPicUrl = picUrl;
    picUrl = newPicUrl;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PageGeneratorLanguarePackage.PICTURE__PIC_URL, oldPicUrl, picUrl));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PageGeneratorLanguarePackage.PICTURE__SIZE:
        return basicSetSize(null, msgs);
      case PageGeneratorLanguarePackage.PICTURE__LOCATION:
        return basicSetLocation(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PageGeneratorLanguarePackage.PICTURE__SIZE:
        return getSize();
      case PageGeneratorLanguarePackage.PICTURE__ALT:
        return getAlt();
      case PageGeneratorLanguarePackage.PICTURE__LOCATION:
        return getLocation();
      case PageGeneratorLanguarePackage.PICTURE__LPADDING:
        return getLpadding();
      case PageGeneratorLanguarePackage.PICTURE__RPADDING:
        return getRpadding();
      case PageGeneratorLanguarePackage.PICTURE__TPADDING:
        return getTpadding();
      case PageGeneratorLanguarePackage.PICTURE__BPADDING:
        return getBpadding();
      case PageGeneratorLanguarePackage.PICTURE__PIC_URL:
        return getPicUrl();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PageGeneratorLanguarePackage.PICTURE__SIZE:
        setSize((primarySize)newValue);
        return;
      case PageGeneratorLanguarePackage.PICTURE__ALT:
        setAlt((String)newValue);
        return;
      case PageGeneratorLanguarePackage.PICTURE__LOCATION:
        setLocation((locationexpression)newValue);
        return;
      case PageGeneratorLanguarePackage.PICTURE__LPADDING:
        setLpadding((Integer)newValue);
        return;
      case PageGeneratorLanguarePackage.PICTURE__RPADDING:
        setRpadding((Integer)newValue);
        return;
      case PageGeneratorLanguarePackage.PICTURE__TPADDING:
        setTpadding((Integer)newValue);
        return;
      case PageGeneratorLanguarePackage.PICTURE__BPADDING:
        setBpadding((Integer)newValue);
        return;
      case PageGeneratorLanguarePackage.PICTURE__PIC_URL:
        setPicUrl((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PageGeneratorLanguarePackage.PICTURE__SIZE:
        setSize((primarySize)null);
        return;
      case PageGeneratorLanguarePackage.PICTURE__ALT:
        setAlt(ALT_EDEFAULT);
        return;
      case PageGeneratorLanguarePackage.PICTURE__LOCATION:
        setLocation((locationexpression)null);
        return;
      case PageGeneratorLanguarePackage.PICTURE__LPADDING:
        setLpadding(LPADDING_EDEFAULT);
        return;
      case PageGeneratorLanguarePackage.PICTURE__RPADDING:
        setRpadding(RPADDING_EDEFAULT);
        return;
      case PageGeneratorLanguarePackage.PICTURE__TPADDING:
        setTpadding(TPADDING_EDEFAULT);
        return;
      case PageGeneratorLanguarePackage.PICTURE__BPADDING:
        setBpadding(BPADDING_EDEFAULT);
        return;
      case PageGeneratorLanguarePackage.PICTURE__PIC_URL:
        setPicUrl(PIC_URL_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PageGeneratorLanguarePackage.PICTURE__SIZE:
        return size != null;
      case PageGeneratorLanguarePackage.PICTURE__ALT:
        return ALT_EDEFAULT == null ? alt != null : !ALT_EDEFAULT.equals(alt);
      case PageGeneratorLanguarePackage.PICTURE__LOCATION:
        return location != null;
      case PageGeneratorLanguarePackage.PICTURE__LPADDING:
        return lpadding != LPADDING_EDEFAULT;
      case PageGeneratorLanguarePackage.PICTURE__RPADDING:
        return rpadding != RPADDING_EDEFAULT;
      case PageGeneratorLanguarePackage.PICTURE__TPADDING:
        return tpadding != TPADDING_EDEFAULT;
      case PageGeneratorLanguarePackage.PICTURE__BPADDING:
        return bpadding != BPADDING_EDEFAULT;
      case PageGeneratorLanguarePackage.PICTURE__PIC_URL:
        return PIC_URL_EDEFAULT == null ? picUrl != null : !PIC_URL_EDEFAULT.equals(picUrl);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (alt: ");
    result.append(alt);
    result.append(", Lpadding: ");
    result.append(lpadding);
    result.append(", Rpadding: ");
    result.append(rpadding);
    result.append(", Tpadding: ");
    result.append(tpadding);
    result.append(", Bpadding: ");
    result.append(bpadding);
    result.append(", picUrl: ");
    result.append(picUrl);
    result.append(')');
    return result.toString();
  }

} //PictureImpl
