/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.PageGeneratorLanguarePackage;
import uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.stringDeclaration;
import uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.stringReference;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>string Reference</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.impl.stringReferenceImpl#getStringreference <em>Stringreference</em>}</li>
 * </ul>
 *
 * @generated
 */
public class stringReferenceImpl extends primaryStringImpl implements stringReference
{
  /**
   * The cached value of the '{@link #getStringreference() <em>Stringreference</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStringreference()
   * @generated
   * @ordered
   */
  protected stringDeclaration stringreference;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected stringReferenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PageGeneratorLanguarePackage.Literals.STRING_REFERENCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public stringDeclaration getStringreference()
  {
    if (stringreference != null && stringreference.eIsProxy())
    {
      InternalEObject oldStringreference = (InternalEObject)stringreference;
      stringreference = (stringDeclaration)eResolveProxy(oldStringreference);
      if (stringreference != oldStringreference)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PageGeneratorLanguarePackage.STRING_REFERENCE__STRINGREFERENCE, oldStringreference, stringreference));
      }
    }
    return stringreference;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public stringDeclaration basicGetStringreference()
  {
    return stringreference;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStringreference(stringDeclaration newStringreference)
  {
    stringDeclaration oldStringreference = stringreference;
    stringreference = newStringreference;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PageGeneratorLanguarePackage.STRING_REFERENCE__STRINGREFERENCE, oldStringreference, stringreference));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PageGeneratorLanguarePackage.STRING_REFERENCE__STRINGREFERENCE:
        if (resolve) return getStringreference();
        return basicGetStringreference();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PageGeneratorLanguarePackage.STRING_REFERENCE__STRINGREFERENCE:
        setStringreference((stringDeclaration)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PageGeneratorLanguarePackage.STRING_REFERENCE__STRINGREFERENCE:
        setStringreference((stringDeclaration)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PageGeneratorLanguarePackage.STRING_REFERENCE__STRINGREFERENCE:
        return stringreference != null;
    }
    return super.eIsSet(featureID);
  }

} //stringReferenceImpl
