/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.mdd.cw2.pageGenerator.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.pageGenerator.ui.internal.PageGeneratorActivator;

public class PageGeneratorLanguareUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PageGeneratorActivator.getInstance().getInjector("uk.ac.kcl.mdd.cw2.pageGenerator.PageGeneratorLanguare");
	}

}
