/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Body</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.Body#getBodyElements <em>Body Elements</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.PageGeneratorLanguarePackage#getBody()
 * @model
 * @generated
 */
public interface Body extends pageElement
{
  /**
   * Returns the value of the '<em><b>Body Elements</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.bodyElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body Elements</em>' containment reference list.
   * @see uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.PageGeneratorLanguarePackage#getBody_BodyElements()
   * @model containment="true"
   * @generated
   */
  EList<bodyElement> getBodyElements();

} // Body
