/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Colour Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.ColourExpression#getColour <em>Colour</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.PageGeneratorLanguarePackage#getColourExpression()
 * @model
 * @generated
 */
public interface ColourExpression extends primaryColour
{
  /**
   * Returns the value of the '<em><b>Colour</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Colour</em>' reference.
   * @see #setColour(ColourRGB)
   * @see uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.PageGeneratorLanguarePackage#getColourExpression_Colour()
   * @model
   * @generated
   */
  ColourRGB getColour();

  /**
   * Sets the value of the '{@link uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.ColourExpression#getColour <em>Colour</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Colour</em>' reference.
   * @see #getColour()
   * @generated
   */
  void setColour(ColourRGB value);

} // ColourExpression
