/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Head</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.Head#getHeadElements <em>Head Elements</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.PageGeneratorLanguarePackage#getHead()
 * @model
 * @generated
 */
public interface Head extends pageElement
{
  /**
   * Returns the value of the '<em><b>Head Elements</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.headElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Head Elements</em>' containment reference list.
   * @see uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.PageGeneratorLanguarePackage#getHead_HeadElements()
   * @model containment="true"
   * @generated
   */
  EList<headElement> getHeadElements();

} // Head
