/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.PageGeneratorLanguarePackage
 * @generated
 */
public interface PageGeneratorLanguareFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PageGeneratorLanguareFactory eINSTANCE = uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.impl.PageGeneratorLanguareFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Web Page</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Web Page</em>'.
   * @generated
   */
  WebPage createWebPage();

  /**
   * Returns a new object of class '<em>page Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>page Element</em>'.
   * @generated
   */
  pageElement createpageElement();

  /**
   * Returns a new object of class '<em>Head</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Head</em>'.
   * @generated
   */
  Head createHead();

  /**
   * Returns a new object of class '<em>head Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>head Element</em>'.
   * @generated
   */
  headElement createheadElement();

  /**
   * Returns a new object of class '<em>Title</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Title</em>'.
   * @generated
   */
  Title createTitle();

  /**
   * Returns a new object of class '<em>Label</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Label</em>'.
   * @generated
   */
  Label createLabel();

  /**
   * Returns a new object of class '<em>Body</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Body</em>'.
   * @generated
   */
  Body createBody();

  /**
   * Returns a new object of class '<em>body Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>body Element</em>'.
   * @generated
   */
  bodyElement createbodyElement();

  /**
   * Returns a new object of class '<em>Heading</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Heading</em>'.
   * @generated
   */
  Heading createHeading();

  /**
   * Returns a new object of class '<em>Link</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Link</em>'.
   * @generated
   */
  Link createLink();

  /**
   * Returns a new object of class '<em>Picture</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Picture</em>'.
   * @generated
   */
  Picture createPicture();

  /**
   * Returns a new object of class '<em>Text</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Text</em>'.
   * @generated
   */
  Text createText();

  /**
   * Returns a new object of class '<em>Section</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Section</em>'.
   * @generated
   */
  Section createSection();

  /**
   * Returns a new object of class '<em>locationexpression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>locationexpression</em>'.
   * @generated
   */
  locationexpression createlocationexpression();

  /**
   * Returns a new object of class '<em>primary Size</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>primary Size</em>'.
   * @generated
   */
  primarySize createprimarySize();

  /**
   * Returns a new object of class '<em>Size Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Size Declaration</em>'.
   * @generated
   */
  SizeDeclaration createSizeDeclaration();

  /**
   * Returns a new object of class '<em>size Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>size Value</em>'.
   * @generated
   */
  sizeValue createsizeValue();

  /**
   * Returns a new object of class '<em>Size Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Size Expression</em>'.
   * @generated
   */
  SizeExpression createSizeExpression();

  /**
   * Returns a new object of class '<em>primary Colour</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>primary Colour</em>'.
   * @generated
   */
  primaryColour createprimaryColour();

  /**
   * Returns a new object of class '<em>colour Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>colour Value</em>'.
   * @generated
   */
  colourValue createcolourValue();

  /**
   * Returns a new object of class '<em>Colour RGB</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Colour RGB</em>'.
   * @generated
   */
  ColourRGB createColourRGB();

  /**
   * Returns a new object of class '<em>Colour Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Colour Expression</em>'.
   * @generated
   */
  ColourExpression createColourExpression();

  /**
   * Returns a new object of class '<em>Content</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Content</em>'.
   * @generated
   */
  Content createContent();

  /**
   * Returns a new object of class '<em>primary String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>primary String</em>'.
   * @generated
   */
  primaryString createprimaryString();

  /**
   * Returns a new object of class '<em>string Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>string Value</em>'.
   * @generated
   */
  stringValue createstringValue();

  /**
   * Returns a new object of class '<em>string Reference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>string Reference</em>'.
   * @generated
   */
  stringReference createstringReference();

  /**
   * Returns a new object of class '<em>string Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>string Declaration</em>'.
   * @generated
   */
  stringDeclaration createstringDeclaration();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  PageGeneratorLanguarePackage getPageGeneratorLanguarePackage();

} //PageGeneratorLanguareFactory
