/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>primary String</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.PageGeneratorLanguarePackage#getprimaryString()
 * @model
 * @generated
 */
public interface primaryString extends Content
{
} // primaryString
