/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>string Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.stringReference#getStringreference <em>Stringreference</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.PageGeneratorLanguarePackage#getstringReference()
 * @model
 * @generated
 */
public interface stringReference extends primaryString
{
  /**
   * Returns the value of the '<em><b>Stringreference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stringreference</em>' reference.
   * @see #setStringreference(stringDeclaration)
   * @see uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.PageGeneratorLanguarePackage#getstringReference_Stringreference()
   * @model
   * @generated
   */
  stringDeclaration getStringreference();

  /**
   * Sets the value of the '{@link uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.stringReference#getStringreference <em>Stringreference</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Stringreference</em>' reference.
   * @see #getStringreference()
   * @generated
   */
  void setStringreference(stringDeclaration value);

} // stringReference
