/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Web Page</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.WebPage#getPageElements <em>Page Elements</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.PageGeneratorLanguarePackage#getWebPage()
 * @model
 * @generated
 */
public interface WebPage extends EObject
{
  /**
   * Returns the value of the '<em><b>Page Elements</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.pageElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Page Elements</em>' containment reference list.
   * @see uk.ac.kcl.mdd.cw2.pageGenerator.pageGeneratorLanguare.PageGeneratorLanguarePackage#getWebPage_PageElements()
   * @model containment="true"
   * @generated
   */
  EList<pageElement> getPageElements();

} // WebPage
