/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.mdd.cw2.pageGenerator.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import uk.ac.kcl.mdd.cw2.pageGenerator.ide.contentassist.antlr.internal.InternalPageGeneratorLanguareParser;
import uk.ac.kcl.mdd.cw2.pageGenerator.services.PageGeneratorLanguareGrammarAccess;

public class PageGeneratorLanguareParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(PageGeneratorLanguareGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, PageGeneratorLanguareGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getPageElementAccess().getAlternatives(), "rule__PageElement__Alternatives");
			builder.put(grammarAccess.getHeadElementAccess().getAlternatives(), "rule__HeadElement__Alternatives");
			builder.put(grammarAccess.getBodyElementAccess().getAlternatives(), "rule__BodyElement__Alternatives");
			builder.put(grammarAccess.getPrimarySizeAccess().getAlternatives(), "rule__PrimarySize__Alternatives");
			builder.put(grammarAccess.getPrimaryColourAccess().getAlternatives(), "rule__PrimaryColour__Alternatives");
			builder.put(grammarAccess.getContentAccess().getSeparatorAlternatives_1_1_0(), "rule__Content__SeparatorAlternatives_1_1_0");
			builder.put(grammarAccess.getPrimaryStringAccess().getAlternatives(), "rule__PrimaryString__Alternatives");
			builder.put(grammarAccess.getHeadAccess().getGroup(), "rule__Head__Group__0");
			builder.put(grammarAccess.getTitleAccess().getGroup(), "rule__Title__Group__0");
			builder.put(grammarAccess.getLabelAccess().getGroup(), "rule__Label__Group__0");
			builder.put(grammarAccess.getBodyAccess().getGroup(), "rule__Body__Group__0");
			builder.put(grammarAccess.getHeadingAccess().getGroup(), "rule__Heading__Group__0");
			builder.put(grammarAccess.getHeadingAccess().getGroup_7(), "rule__Heading__Group_7__0");
			builder.put(grammarAccess.getHeadingAccess().getGroup_8(), "rule__Heading__Group_8__0");
			builder.put(grammarAccess.getHeadingAccess().getGroup_9(), "rule__Heading__Group_9__0");
			builder.put(grammarAccess.getHeadingAccess().getGroup_10(), "rule__Heading__Group_10__0");
			builder.put(grammarAccess.getHeadingAccess().getGroup_11(), "rule__Heading__Group_11__0");
			builder.put(grammarAccess.getHeadingAccess().getGroup_12(), "rule__Heading__Group_12__0");
			builder.put(grammarAccess.getLinkAccess().getGroup(), "rule__Link__Group__0");
			builder.put(grammarAccess.getLinkAccess().getGroup_3(), "rule__Link__Group_3__0");
			builder.put(grammarAccess.getLinkAccess().getGroup_4(), "rule__Link__Group_4__0");
			builder.put(grammarAccess.getLinkAccess().getGroup_5(), "rule__Link__Group_5__0");
			builder.put(grammarAccess.getLinkAccess().getGroup_6(), "rule__Link__Group_6__0");
			builder.put(grammarAccess.getLinkAccess().getGroup_7(), "rule__Link__Group_7__0");
			builder.put(grammarAccess.getLinkAccess().getGroup_8(), "rule__Link__Group_8__0");
			builder.put(grammarAccess.getLinkAccess().getGroup_9(), "rule__Link__Group_9__0");
			builder.put(grammarAccess.getLinkAccess().getGroup_10(), "rule__Link__Group_10__0");
			builder.put(grammarAccess.getPictureAccess().getGroup(), "rule__Picture__Group__0");
			builder.put(grammarAccess.getPictureAccess().getGroup_3(), "rule__Picture__Group_3__0");
			builder.put(grammarAccess.getPictureAccess().getGroup_4(), "rule__Picture__Group_4__0");
			builder.put(grammarAccess.getPictureAccess().getGroup_5(), "rule__Picture__Group_5__0");
			builder.put(grammarAccess.getPictureAccess().getGroup_6(), "rule__Picture__Group_6__0");
			builder.put(grammarAccess.getPictureAccess().getGroup_7(), "rule__Picture__Group_7__0");
			builder.put(grammarAccess.getPictureAccess().getGroup_8(), "rule__Picture__Group_8__0");
			builder.put(grammarAccess.getPictureAccess().getGroup_9(), "rule__Picture__Group_9__0");
			builder.put(grammarAccess.getTextAccess().getGroup(), "rule__Text__Group__0");
			builder.put(grammarAccess.getTextAccess().getGroup_3(), "rule__Text__Group_3__0");
			builder.put(grammarAccess.getTextAccess().getGroup_4(), "rule__Text__Group_4__0");
			builder.put(grammarAccess.getTextAccess().getGroup_5(), "rule__Text__Group_5__0");
			builder.put(grammarAccess.getTextAccess().getGroup_6(), "rule__Text__Group_6__0");
			builder.put(grammarAccess.getTextAccess().getGroup_7(), "rule__Text__Group_7__0");
			builder.put(grammarAccess.getTextAccess().getGroup_8(), "rule__Text__Group_8__0");
			builder.put(grammarAccess.getTextAccess().getGroup_9(), "rule__Text__Group_9__0");
			builder.put(grammarAccess.getSectionAccess().getGroup(), "rule__Section__Group__0");
			builder.put(grammarAccess.getSectionAccess().getGroup_3(), "rule__Section__Group_3__0");
			builder.put(grammarAccess.getSectionAccess().getGroup_4(), "rule__Section__Group_4__0");
			builder.put(grammarAccess.getSectionAccess().getGroup_5(), "rule__Section__Group_5__0");
			builder.put(grammarAccess.getSectionAccess().getGroup_6(), "rule__Section__Group_6__0");
			builder.put(grammarAccess.getSectionAccess().getGroup_7(), "rule__Section__Group_7__0");
			builder.put(grammarAccess.getSectionAccess().getGroup_8(), "rule__Section__Group_8__0");
			builder.put(grammarAccess.getSectionAccess().getGroup_9(), "rule__Section__Group_9__0");
			builder.put(grammarAccess.getSectionAccess().getGroup_10(), "rule__Section__Group_10__0");
			builder.put(grammarAccess.getSizeDeclarationAccess().getGroup(), "rule__SizeDeclaration__Group__0");
			builder.put(grammarAccess.getSizeValueAccess().getGroup(), "rule__SizeValue__Group__0");
			builder.put(grammarAccess.getColourRGBAccess().getGroup(), "rule__ColourRGB__Group__0");
			builder.put(grammarAccess.getContentAccess().getGroup(), "rule__Content__Group__0");
			builder.put(grammarAccess.getContentAccess().getGroup_1(), "rule__Content__Group_1__0");
			builder.put(grammarAccess.getStringDeclarationAccess().getGroup(), "rule__StringDeclaration__Group__0");
			builder.put(grammarAccess.getStringDeclarationAccess().getGroup_3(), "rule__StringDeclaration__Group_3__0");
			builder.put(grammarAccess.getStringDeclarationAccess().getGroup_4(), "rule__StringDeclaration__Group_4__0");
			builder.put(grammarAccess.getWebPageAccess().getPageElementsAssignment(), "rule__WebPage__PageElementsAssignment");
			builder.put(grammarAccess.getHeadAccess().getHeadElementsAssignment_3(), "rule__Head__HeadElementsAssignment_3");
			builder.put(grammarAccess.getTitleAccess().getNameAssignment_2(), "rule__Title__NameAssignment_2");
			builder.put(grammarAccess.getLabelAccess().getNameAssignment_2(), "rule__Label__NameAssignment_2");
			builder.put(grammarAccess.getLabelAccess().getLabelAssignment_6(), "rule__Label__LabelAssignment_6");
			builder.put(grammarAccess.getBodyAccess().getBodyElementsAssignment_3(), "rule__Body__BodyElementsAssignment_3");
			builder.put(grammarAccess.getHeadingAccess().getNameAssignment_1(), "rule__Heading__NameAssignment_1");
			builder.put(grammarAccess.getHeadingAccess().getIndexAssignment_5(), "rule__Heading__IndexAssignment_5");
			builder.put(grammarAccess.getHeadingAccess().getFontColorAssignment_7_2(), "rule__Heading__FontColorAssignment_7_2");
			builder.put(grammarAccess.getHeadingAccess().getLocationAssignment_8_2(), "rule__Heading__LocationAssignment_8_2");
			builder.put(grammarAccess.getHeadingAccess().getLpaddingAssignment_9_2(), "rule__Heading__LpaddingAssignment_9_2");
			builder.put(grammarAccess.getHeadingAccess().getRpaddingAssignment_10_2(), "rule__Heading__RpaddingAssignment_10_2");
			builder.put(grammarAccess.getHeadingAccess().getTpaddingAssignment_11_2(), "rule__Heading__TpaddingAssignment_11_2");
			builder.put(grammarAccess.getHeadingAccess().getBpaddingAssignment_12_2(), "rule__Heading__BpaddingAssignment_12_2");
			builder.put(grammarAccess.getHeadingAccess().getTitleAssignment_15(), "rule__Heading__TitleAssignment_15");
			builder.put(grammarAccess.getLinkAccess().getNameAssignment_1(), "rule__Link__NameAssignment_1");
			builder.put(grammarAccess.getLinkAccess().getTargetAssignment_3_2(), "rule__Link__TargetAssignment_3_2");
			builder.put(grammarAccess.getLinkAccess().getLpaddingAssignment_4_2(), "rule__Link__LpaddingAssignment_4_2");
			builder.put(grammarAccess.getLinkAccess().getRpaddingAssignment_5_2(), "rule__Link__RpaddingAssignment_5_2");
			builder.put(grammarAccess.getLinkAccess().getTpaddingAssignment_6_2(), "rule__Link__TpaddingAssignment_6_2");
			builder.put(grammarAccess.getLinkAccess().getBpaddingAssignment_7_2(), "rule__Link__BpaddingAssignment_7_2");
			builder.put(grammarAccess.getLinkAccess().getFontColorAssignment_8_2(), "rule__Link__FontColorAssignment_8_2");
			builder.put(grammarAccess.getLinkAccess().getFontSizeAssignment_9_2(), "rule__Link__FontSizeAssignment_9_2");
			builder.put(grammarAccess.getLinkAccess().getLocationAssignment_10_2(), "rule__Link__LocationAssignment_10_2");
			builder.put(grammarAccess.getLinkAccess().getUrlAssignment_13(), "rule__Link__UrlAssignment_13");
			builder.put(grammarAccess.getPictureAccess().getNameAssignment_1(), "rule__Picture__NameAssignment_1");
			builder.put(grammarAccess.getPictureAccess().getSizeAssignment_3_2(), "rule__Picture__SizeAssignment_3_2");
			builder.put(grammarAccess.getPictureAccess().getAltAssignment_4_2(), "rule__Picture__AltAssignment_4_2");
			builder.put(grammarAccess.getPictureAccess().getLocationAssignment_5_2(), "rule__Picture__LocationAssignment_5_2");
			builder.put(grammarAccess.getPictureAccess().getLpaddingAssignment_6_2(), "rule__Picture__LpaddingAssignment_6_2");
			builder.put(grammarAccess.getPictureAccess().getRpaddingAssignment_7_2(), "rule__Picture__RpaddingAssignment_7_2");
			builder.put(grammarAccess.getPictureAccess().getTpaddingAssignment_8_2(), "rule__Picture__TpaddingAssignment_8_2");
			builder.put(grammarAccess.getPictureAccess().getBpaddingAssignment_9_2(), "rule__Picture__BpaddingAssignment_9_2");
			builder.put(grammarAccess.getPictureAccess().getPicUrlAssignment_12(), "rule__Picture__PicUrlAssignment_12");
			builder.put(grammarAccess.getTextAccess().getNameAssignment_1(), "rule__Text__NameAssignment_1");
			builder.put(grammarAccess.getTextAccess().getFontColorAssignment_3_2(), "rule__Text__FontColorAssignment_3_2");
			builder.put(grammarAccess.getTextAccess().getFontSizeAssignment_4_2(), "rule__Text__FontSizeAssignment_4_2");
			builder.put(grammarAccess.getTextAccess().getLocationAssignment_5_2(), "rule__Text__LocationAssignment_5_2");
			builder.put(grammarAccess.getTextAccess().getLpaddingAssignment_6_2(), "rule__Text__LpaddingAssignment_6_2");
			builder.put(grammarAccess.getTextAccess().getRpaddingAssignment_7_2(), "rule__Text__RpaddingAssignment_7_2");
			builder.put(grammarAccess.getTextAccess().getTpaddingAssignment_8_2(), "rule__Text__TpaddingAssignment_8_2");
			builder.put(grammarAccess.getTextAccess().getBpaddingAssignment_9_2(), "rule__Text__BpaddingAssignment_9_2");
			builder.put(grammarAccess.getTextAccess().getContentAssignment_12(), "rule__Text__ContentAssignment_12");
			builder.put(grammarAccess.getSectionAccess().getNameAssignment_1(), "rule__Section__NameAssignment_1");
			builder.put(grammarAccess.getSectionAccess().getBgColorAssignment_3_2(), "rule__Section__BgColorAssignment_3_2");
			builder.put(grammarAccess.getSectionAccess().getSizeAssignment_4_2(), "rule__Section__SizeAssignment_4_2");
			builder.put(grammarAccess.getSectionAccess().getLocationAssignment_5_2(), "rule__Section__LocationAssignment_5_2");
			builder.put(grammarAccess.getSectionAccess().getTextLocationAssignment_6_2(), "rule__Section__TextLocationAssignment_6_2");
			builder.put(grammarAccess.getSectionAccess().getLpaddingAssignment_7_2(), "rule__Section__LpaddingAssignment_7_2");
			builder.put(grammarAccess.getSectionAccess().getRpaddingAssignment_8_2(), "rule__Section__RpaddingAssignment_8_2");
			builder.put(grammarAccess.getSectionAccess().getTpaddingAssignment_9_2(), "rule__Section__TpaddingAssignment_9_2");
			builder.put(grammarAccess.getSectionAccess().getBpaddingAssignment_10_2(), "rule__Section__BpaddingAssignment_10_2");
			builder.put(grammarAccess.getSectionAccess().getBodyElementsAssignment_13(), "rule__Section__BodyElementsAssignment_13");
			builder.put(grammarAccess.getLocationexpressionAccess().getLocationAssignment(), "rule__Locationexpression__LocationAssignment");
			builder.put(grammarAccess.getSizeDeclarationAccess().getNameAssignment_1(), "rule__SizeDeclaration__NameAssignment_1");
			builder.put(grammarAccess.getSizeDeclarationAccess().getWidthAssignment_3(), "rule__SizeDeclaration__WidthAssignment_3");
			builder.put(grammarAccess.getSizeDeclarationAccess().getHeightAssignment_5(), "rule__SizeDeclaration__HeightAssignment_5");
			builder.put(grammarAccess.getSizeValueAccess().getWidthAssignment_0(), "rule__SizeValue__WidthAssignment_0");
			builder.put(grammarAccess.getSizeValueAccess().getHeightAssignment_2(), "rule__SizeValue__HeightAssignment_2");
			builder.put(grammarAccess.getSizeExpressionAccess().getSizeAssignment(), "rule__SizeExpression__SizeAssignment");
			builder.put(grammarAccess.getColourValueAccess().getColourAssignment(), "rule__ColourValue__ColourAssignment");
			builder.put(grammarAccess.getColourRGBAccess().getNameAssignment_2(), "rule__ColourRGB__NameAssignment_2");
			builder.put(grammarAccess.getColourRGBAccess().getRgbAssignment_4(), "rule__ColourRGB__RgbAssignment_4");
			builder.put(grammarAccess.getColourRGBAccess().getRedAssignment_5(), "rule__ColourRGB__RedAssignment_5");
			builder.put(grammarAccess.getColourRGBAccess().getGreenAssignment_7(), "rule__ColourRGB__GreenAssignment_7");
			builder.put(grammarAccess.getColourRGBAccess().getBlueAssignment_9(), "rule__ColourRGB__BlueAssignment_9");
			builder.put(grammarAccess.getColourExpressionAccess().getColourAssignment(), "rule__ColourExpression__ColourAssignment");
			builder.put(grammarAccess.getContentAccess().getSeparatorAssignment_1_1(), "rule__Content__SeparatorAssignment_1_1");
			builder.put(grammarAccess.getContentAccess().getRightAssignment_1_2(), "rule__Content__RightAssignment_1_2");
			builder.put(grammarAccess.getStringValueAccess().getValAssignment(), "rule__StringValue__ValAssignment");
			builder.put(grammarAccess.getStringReferenceAccess().getStringreferenceAssignment(), "rule__StringReference__StringreferenceAssignment");
			builder.put(grammarAccess.getStringDeclarationAccess().getNameAssignment_1(), "rule__StringDeclaration__NameAssignment_1");
			builder.put(grammarAccess.getStringDeclarationAccess().getFontColorAssignment_3_2(), "rule__StringDeclaration__FontColorAssignment_3_2");
			builder.put(grammarAccess.getStringDeclarationAccess().getFontSizeAssignment_4_2(), "rule__StringDeclaration__FontSizeAssignment_4_2");
			builder.put(grammarAccess.getStringDeclarationAccess().getWordAssignment_7(), "rule__StringDeclaration__WordAssignment_7");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private PageGeneratorLanguareGrammarAccess grammarAccess;

	@Override
	protected InternalPageGeneratorLanguareParser createParser() {
		InternalPageGeneratorLanguareParser result = new InternalPageGeneratorLanguareParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public PageGeneratorLanguareGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PageGeneratorLanguareGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
