/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.mdd.cw2.pageGenerator.ide;


/**
 * Use this class to register ide components.
 */
public class PageGeneratorLanguareIdeModule extends AbstractPageGeneratorLanguareIdeModule {
}
